# Generated by Django 5.0.4 on 2024-06-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_shippingaddress_shipping_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
